### ISSUE TITLE
Bump cdt-gdb-vscode version on OpenVSX to 1.0.3

### ISSUE THREAD

**Issue by aarontan-mchp** [eclipse-cdt-cloud/cdt-gdb-vscode#125]
Hi @jonahgraham,

Hope you are doing well. We would like to pull in the changes from https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/pull/120 into our application via OpenVSX, however the versions available there only seem to go up to 0.0.108: https://open-vsx.org/extension/eclipse-cdt/cdt-gdb-vscode

Let me know if I am missing something obvious. Thanks!

**Comment by jonahgraham** [comment]
Thanks @aarontan-mchp for bringing this to my attention. Open VSX has a bunch of scripts that auto-publish the latest version. It looks like this extension has an incompatibility with that publishing script as I can see this error ([link](https://github.com/EclipseFdn/publish-extensions/actions/runs/12308976557/job/34355270361#step:12:1035))

     Error: Both a .vscodeignore file and a "files" property in package.json were found. VSCE does not support combining both strategies. Either remove the .vscodeignore file or the "files" property in package.json.

This looks like something changed on open vsx since we last published successfully. But I suspect that we'll need to change something here, so I'll leave this open to track our changes.

**Comment by jonahgraham** [comment]
@aarontan-mchp I think I have fixed the problem, please let me know if it worked. You will need to wait until the next time the publishing script runs, which I [expect to be a 3am](https://github.com/EclipseFdn/publish-extensions/blob/86a1fec1831bbe5e2977a3e78c4769c6d2e67de7/.github/workflows/publish-extensions.yml#L5-L6). You can see the actions here https://github.com/EclipseFdn/publish-extensions/actions

**Comment by jonahgraham** [comment]
@aarontan-mchp https://open-vsx.org/extension/eclipse-cdt/cdt-gdb-vscode now contains v1.0.4. Please let me know if it works well for you.

**Comment by aarontan-mchp** [comment]
@jonahgraham Thanks for the quick update! We are currently working to pull in the changes and will let you know if everything looks good. Should be able to let you know by EOD today or tomorrow.

**Comment by aarontan-mchp** [comment]
Hi @jonahgraham, everything seems to be in order on our end. Will open a new issue if there anything unexpected occurs, since this issue is to publish the latest version to OpenVSX. Thanks again for handling it so quickly!
