### ISSUE TITLE
Not breaking at Breakpoint when Debugging

### ISSUE THREAD

**Issue by SreeRanjani** [eclipse-cdt-cloud/cdt-gdb-vscode#67]
When I try to use cdt-gdb-vscode to achieve debugging of cpp files in Theia with GDB, the code doesn't break at breakpoint, the breakpoint is faded and when I hover over a message saying r **-break-insert: Unknown option ``-source''** is shown . I use the below Launch.json configuratoin

> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>         "type": "gdb",
>         "request": "launch",
>         "name": "Debug (GDB)",
>         "program": "${workspaceFolder}\\HelloWorld.exe"
>     }
> ]
> }

Error (On hover near breakpoint):
![image](https://user-images.githubusercontent.com/53086384/164750760-841c2eaf-a912-4829-87b6-549719f905ff.png)

**Comment by jonahgraham** [comment]
Hi @SreeRanjani - as it turns out I just fixed this issue a few days ago (see #187)

Specifically this commit:
https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/188/commits/13a9ecc5f023b7e85922aa46e13123541ced9c79

As you can see from #187 the adapter was originally written for GDB >= 8.0, presumably you are using some older version of GDB.

Are you using GDB 7.6 or later?

**Comment by SreeRanjani** [comment]
Thanks, I was using GDB v7.6.1, I was able to get this working by upgrading the version of GDB. Thanks for support
